CREATE TABLE IF NOT EXISTS `Roles` (
`id` bigint NOT NULL AUTO_INCREMENT,
`name`varchar(10) NOT NULL DEFAULT 0,
`status` tinyint NOT NULL DEFAULT 0,
`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
KEY `idx_roles_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;